// client-portal/src/components/layout/Header.tsx
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { 
  ShieldCheck, 
  ShoppingCart, 
  Sun, 
  Moon, 
  Store as StoreIcon, 
  FileCode, 
  Clock, 
  ChevronDown, 
  LogOut, 
  KeyRound, 
  User as UserIcon, 
  ShoppingBag, 
  Crown, 
  Award, 
  Menu, 
  X, 
  ChevronRight,
  Sparkles
} from 'lucide-react';
import { useAppDispatch, useAppSelector } from '../../store/store';
import { toggleTheme } from '../../store/slices/themeSlice';
import { toggleCartDrawer } from '../../store/slices/cartSlice';
import { setActiveStore } from '../../store/slices/tenantSlice';
import { logout } from '../../store/slices/authSlice';
import { getUserGatedTier, getUserLifetimeSpend, GATED_TIERS } from '../../utils/tierUtils';

export const Header: React.FC = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const location = useLocation();
  const isDark = useAppSelector((state) => state.theme.isDark);
  const { currentUser, isAuthenticated } = useAppSelector((state) => state.auth);
  const { stores, activeStoreId } = useAppSelector((state) => state.tenant);
  const { items } = useAppSelector((state) => state.cart);
  const { orders } = useAppSelector((state) => state.order);

  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const totalCartCount = items.reduce((acc, item) => acc + item.quantity, 0);
  const accessibleStoresCount = currentUser?.accessibleStores?.length || 0;
  const activeStore = stores.find((s) => s.id === activeStoreId);

  // Compute User Spend Tier
  const userGatedTier = getUserGatedTier(currentUser, orders);
  const tierConfig = GATED_TIERS[userGatedTier];
  const totalSpent = getUserLifetimeSpend(currentUser, orders);

  return (
    <header className="sticky top-0 z-40 w-full backdrop-blur-md bg-white/90 dark:bg-[#0b131c]/90 border-b border-slate-200/80 dark:border-slate-800 transition-colors duration-200 shadow-xs">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          
          {/* Left: Brand Logo & Navigation */}
          <div className="flex items-center space-x-5">
            <button
              onClick={() => {
                dispatch(setActiveStore(null));
                navigate('/');
              }}
              className="flex items-center space-x-3 group text-left cursor-pointer focus:outline-none"
            >
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#212832] via-[#212832] to-[#2988c8] flex items-center justify-center text-white shadow-sm ring-1 ring-white/10 group-hover:scale-105 transition-transform duration-200">
                <ShieldCheck className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <div className="flex items-center space-x-2">
                  <span className="font-extrabold text-lg tracking-tight text-slate-900 dark:text-white">
                    Nexus<span className="text-[#2988c8]">Gate</span>
                  </span>
                  <span className="px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase rounded-md bg-[#2988c8]/10 text-[#2988c8] dark:text-amber-400 border border-[#2988c8]/25">
                    PORTAL
                  </span>
                </div>
                <p className="text-[11px] font-medium text-slate-500 dark:text-slate-400 leading-none mt-0.5">
                  Verified Store Directory
                </p>
              </div>
            </button>

            {/* Desktop Navigation Links */}
            <nav className="hidden md:flex items-center space-x-1 pl-4 border-l border-slate-200 dark:border-slate-800">
              <button
                onClick={() => {
                  dispatch(setActiveStore(null));
                  navigate('/');
                }}
                className={`px-3.5 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center space-x-1.5 active:scale-95 ${
                  location.pathname === '/'
                    ? 'text-white bg-[#212832] dark:bg-[#2988c8] shadow-xs'
                    : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800/60'
                }`}
              >
                <StoreIcon className="w-4 h-4" />
                <span>Invited Stores</span>
                <span className={`ml-1 text-[10px] px-1.5 py-0.2 rounded-full font-mono font-bold ${
                  location.pathname === '/' ? 'bg-white/20 text-white' : 'bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300'
                }`}>
                  {accessibleStoresCount}
                </span>
              </button>

              {activeStore && (
                <button
                  onClick={() => navigate('/store')}
                  className={`px-3.5 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center space-x-1.5 active:scale-95 ${
                    location.pathname === '/store'
                      ? 'text-white bg-[#212832] dark:bg-[#2988c8] shadow-xs'
                      : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800/60'
                  }`}
                >
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                  <span className="truncate max-w-[130px]">{activeStore.name}</span>
                </button>
              )}

              <button
                onClick={() => navigate('/orders')}
                className={`px-3.5 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center space-x-1.5 active:scale-95 ${
                  location.pathname === '/orders'
                    ? 'text-white bg-[#212832] dark:bg-[#2988c8] shadow-xs'
                    : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800/60'
                }`}
              >
                <Clock className="w-4 h-4" />
                <span>Orders</span>
                {orders.some((o) => o.status === 'Pending') && (
                  <span className="px-1.5 py-0.2 text-[10px] font-bold rounded-full bg-[#2988c8] text-white animate-subtle-pulse">
                    {orders.filter((o) => o.status === 'Pending').length}
                  </span>
                )}
              </button>

              <button
                onClick={() => navigate('/profile')}
                className={`px-3.5 py-2 text-xs font-bold rounded-xl transition-all cursor-pointer flex items-center space-x-1.5 active:scale-95 ${
                  location.pathname === '/profile'
                    ? 'text-white bg-[#212832] dark:bg-[#2988c8] shadow-xs'
                    : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800/60'
                }`}
              >
                <UserIcon className="w-4 h-4" />
                <span>Profile & Tier</span>
              </button>
            </nav>
          </div>

          {/* Right Action Bar */}
          <div className="flex items-center space-x-2">

            {/* Dark/Light Mode Toggle Button */}
            <button
              onClick={() => dispatch(toggleTheme())}
              aria-label="Toggle light and dark mode"
              className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800/80 text-slate-700 dark:text-slate-200 hover:text-slate-900 dark:hover:text-white border border-slate-200 dark:border-slate-700 transition-all cursor-pointer shadow-xs active:scale-95"
              title={isDark ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
            >
              {isDark ? (
                <Sun className="w-4 h-4 text-amber-400" />
              ) : (
                <Moon className="w-4 h-4 text-slate-700" />
              )}
            </button>

            {/* Shopping Cart Button */}
            <button
              onClick={() => dispatch(toggleCartDrawer())}
              className="relative flex items-center space-x-2 px-3.5 py-2 rounded-xl bg-[#2988c8] hover:bg-[#d97d10] text-white shadow-sm transition-all duration-150 cursor-pointer active:scale-95 font-bold text-xs"
            >
              <ShoppingCart className="w-4 h-4" />
              <span className="hidden sm:inline">Cart</span>
              {totalCartCount > 0 && (
                <span className="inline-flex items-center justify-center px-1.5 py-0.2 text-[10px] font-black leading-none text-slate-900 bg-amber-300 rounded-full shadow-xs">
                  {totalCartCount}
                </span>
              )}
            </button>

            {/* User Profile & Tier Status */}
            {isAuthenticated && currentUser ? (
              <div className="relative flex items-center space-x-1.5">
                
                {/* Shopper Tier Pill */}
                <button
                  onClick={() => navigate('/profile')}
                  className={`hidden sm:inline-flex items-center space-x-1 px-2.5 py-1.5 rounded-xl text-xs font-black uppercase tracking-wider ${tierConfig.badgeClass} shadow-xs border cursor-pointer hover:opacity-90 active:scale-95 transition-all`}
                  title={`Your Spend Tier is ${userGatedTier} (${tierConfig.discountPercent}% Discount). Click to view breakdown.`}
                >
                  <span>{tierConfig.icon}</span>
                  <span>{userGatedTier} ({tierConfig.discountPercent}%)</span>
                </button>

                <button
                  onClick={() => setIsUserMenuOpen(!isUserMenuOpen)}
                  className="flex items-center space-x-2 p-1 sm:px-2.5 sm:py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/80 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors cursor-pointer"
                >
                  <img
                    src={currentUser.avatarUrl}
                    alt={currentUser.fullName}
                    className="w-7 h-7 rounded-full object-cover ring-2 ring-[#2988c8]/50"
                  />
                  <div className="hidden xl:block text-left text-xs">
                    <p className="font-bold text-slate-800 dark:text-white leading-tight truncate max-w-[110px]">
                      {currentUser.fullName}
                    </p>
                    <p className="text-[10px] text-slate-500 dark:text-slate-400 truncate max-w-[110px]">
                      @{currentUser.username || 'shopper'}
                    </p>
                  </div>
                  <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                </button>

                {/* User Dropdown */}
                {isUserMenuOpen && (
                  <div className="absolute right-0 top-11 mt-2 w-72 rounded-2xl bg-white dark:bg-[#0b131c] border border-slate-200 dark:border-slate-800 shadow-2xl py-2 z-50 animate-in fade-in slide-in-from-top-2">
                    <div className="px-4 py-3 border-b border-slate-100 dark:border-slate-800">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-bold text-slate-900 dark:text-white">
                          {currentUser.fullName}
                        </span>
                        <span className={`px-2 py-0.5 text-[10px] font-black uppercase rounded-full ${tierConfig.badgeClass}`}>
                          {tierConfig.icon} {userGatedTier}
                        </span>
                      </div>
                      <p className="text-xs text-slate-500 dark:text-slate-400 truncate">
                        @{currentUser.username} • {currentUser.email}
                      </p>
                      <div className="mt-2 flex items-center justify-between text-[11px] bg-slate-50 dark:bg-slate-900/60 p-2 rounded-lg border border-slate-100 dark:border-slate-800">
                        <span className="text-slate-500 dark:text-slate-400">Total Spend:</span>
                        <span className="font-mono font-bold text-[#2988c8]">
                          ₹{totalSpent.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                        </span>
                      </div>
                    </div>

                    <div className="px-4 py-2 text-xs border-b border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/30 space-y-1">
                      <div className="flex justify-between text-slate-600 dark:text-slate-400">
                        <span>Cart Discount:</span>
                        <span className="font-bold text-emerald-600 dark:text-emerald-400">
                          {tierConfig.discountPercent}% Off Every Order
                        </span>
                      </div>
                      <div className="flex justify-between text-slate-600 dark:text-slate-400">
                        <span>Shipping Perk:</span>
                        <span className="font-semibold text-slate-800 dark:text-slate-200 truncate max-w-[150px]">
                          {tierConfig.shippingPerk}
                        </span>
                      </div>
                    </div>

                    <div className="p-2 space-y-0.5">
                      <button
                        onClick={() => {
                          setIsUserMenuOpen(false);
                          navigate('/profile');
                        }}
                        className="w-full text-left px-3 py-2 text-xs font-semibold rounded-lg text-slate-800 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center space-x-2 cursor-pointer"
                      >
                        <Award className="w-3.5 h-3.5 text-amber-500" />
                        <span>Spend Tiers & Offers</span>
                      </button>

                      <button
                        onClick={() => {
                          setIsUserMenuOpen(false);
                          navigate('/orders');
                        }}
                        className="w-full text-left px-3 py-2 text-xs font-semibold rounded-lg text-slate-800 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center space-x-2 cursor-pointer"
                      >
                        <Clock className="w-3.5 h-3.5 text-[#2988c8]" />
                        <span>Purchase Order History</span>
                      </button>

                      <button
                        onClick={() => {
                          setIsUserMenuOpen(false);
                          navigate('/login');
                        }}
                        className="w-full text-left px-3 py-2 text-xs font-semibold rounded-lg text-slate-800 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center space-x-2 cursor-pointer"
                      >
                        <KeyRound className="w-3.5 h-3.5 text-amber-500" />
                        <span>Shopper Login Credentials</span>
                      </button>

                      <button
                        onClick={() => {
                          setIsUserMenuOpen(false);
                          dispatch(logout());
                          navigate('/login');
                        }}
                        className="w-full text-left px-3 py-2 text-xs font-semibold rounded-lg text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/30 flex items-center space-x-2 cursor-pointer"
                      >
                        <LogOut className="w-3.5 h-3.5" />
                        <span>Sign Out</span>
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <button
                onClick={() => navigate('/login')}
                className="px-3.5 py-1.5 rounded-xl bg-[#2988c8] hover:bg-[#d97d10] text-white text-xs font-bold transition-colors shadow-xs"
              >
                Sign In
              </button>
            )}

            {/* Mobile Menu Button */}
            <button
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 md:hidden cursor-pointer"
              aria-label="Toggle navigation menu"
            >
              {isMobileMenuOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}
            </button>

          </div>

        </div>
      </div>

      {/* Mobile Drawer Navigation */}
      {isMobileMenuOpen && (
        <div className="md:hidden border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0b131c] px-4 py-3 space-y-2 animate-in slide-in-from-top-1">
          <button
            onClick={() => {
              dispatch(setActiveStore(null));
              navigate('/');
              setIsMobileMenuOpen(false);
            }}
            className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 text-xs font-bold text-slate-800 dark:text-white"
          >
            <div className="flex items-center space-x-2">
              <StoreIcon className="w-4 h-4 text-[#2988c8]" />
              <span>Invited Stores</span>
            </div>
            <span className="px-2 py-0.5 rounded-full bg-[#2988c8]/15 text-[#2988c8] text-[10px] font-bold">
              {accessibleStoresCount} Stores
            </span>
          </button>

          {activeStore && (
            <button
              onClick={() => {
                navigate('/store');
                setIsMobileMenuOpen(false);
              }}
              className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 text-xs font-bold text-slate-800 dark:text-white"
            >
              <div className="flex items-center space-x-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                <span>Active: {activeStore.name}</span>
              </div>
              <ChevronRight className="w-4 h-4 text-slate-400" />
            </button>
          )}

          <button
            onClick={() => {
              navigate('/orders');
              setIsMobileMenuOpen(false);
            }}
            className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 text-xs font-bold text-slate-800 dark:text-white"
          >
            <div className="flex items-center space-x-2">
              <Clock className="w-4 h-4 text-[#2988c8]" />
              <span>Orders & Tracking</span>
            </div>
            {orders.length > 0 && (
              <span className="text-[10px] text-slate-400 font-mono">
                {orders.length} orders
              </span>
            )}
          </button>

          <button
            onClick={() => {
              navigate('/profile');
              setIsMobileMenuOpen(false);
            }}
            className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 text-xs font-bold text-slate-800 dark:text-white"
          >
            <div className="flex items-center space-x-2">
              <UserIcon className="w-4 h-4 text-[#2988c8]" />
              <span>Profile & Spend Tier</span>
            </div>
            <span className="text-[10px] text-amber-500 font-bold">
              {userGatedTier} ({tierConfig.discountPercent}% Off)
            </span>
          </button>
        </div>
      )}
    </header>
  );
};

// admin-portal/src/app/shared/components/header/header.component.ts
import { Component, inject, ChangeDetectionStrategy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthStore } from '../../../core/auth/auth.store';
import { ThemeService } from '../../../core/theme/theme.service';
import { StoreState } from '../../../state/store.state';
import { OrderState } from '../../../state/order.state';
import { StatusBadgeComponent } from '../badge/status-badge.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule, StatusBadgeComponent],
  templateUrl: './header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {
  readonly authStore = inject(AuthStore);
  readonly themeService = inject(ThemeService);
  readonly storeState = inject(StoreState);
  readonly orderState = inject(OrderState);
  private readonly router = inject(Router);

  public isProfileOpen = signal(false);

  public toggleTheme(): void {
    this.themeService.toggleTheme();
  }

  public backToPlatform(): void {
    this.storeState.clearSelectedStore();
    this.router.navigate(['/super-admin/dashboard']);
  }

  public logout(): void {
    this.isProfileOpen.set(false);
    this.authStore.logout();
  }
}

<header class="sticky top-0 z-30 flex items-center justify-between h-16 px-6 bg-white/90 dark:bg-slate-900/90 backdrop-blur border-b border-slate-200 dark:border-slate-800 transition-colors duration-200">
  <!-- Left: Portal Context -->
  <div class="flex items-center space-x-4">
    <div class="flex items-center space-x-3">
      <div class="w-8 h-8 rounded-xl bg-gradient-to-br from-[#0b3c5d] via-[#2988c8] to-[#d97d10] flex items-center justify-center font-extrabold text-white text-xs shadow-sm shadow-[#2988c8]/20">
        GP
      </div>
      <div>
        <div class="flex items-center space-x-2">
          <span class="text-sm font-bold tracking-tight text-slate-900 dark:text-slate-100">GatedPulse Portal</span>
          <span class="text-xs text-slate-400 dark:text-slate-500">/</span>
          @if (authStore.isSuperAdmin() && storeState.selectedStoreId()) {
            <button
              (click)="backToPlatform()"
              class="text-xs font-semibold uppercase tracking-wider text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-950/60 px-2 py-0.5 rounded border border-indigo-200 dark:border-indigo-800/60 hover:bg-indigo-100 dark:hover:bg-indigo-900/40 transition"
            >
              Platform Overview
            </button>
            <span class="text-xs text-slate-400 dark:text-slate-500">/</span>
            <span class="text-xs font-semibold uppercase tracking-wider text-amber-800 dark:text-amber-300 bg-amber-50 dark:bg-amber-950/60 px-2 py-0.5 rounded border border-amber-200 dark:border-amber-800/60">
              {{ storeState.activeStore()?.name }}
            </span>
          } @else if (authStore.isSuperAdmin()) {
            <span class="text-xs font-semibold uppercase tracking-wider text-purple-700 dark:text-purple-300 bg-purple-50 dark:bg-purple-950/60 px-2 py-0.5 rounded border border-purple-200 dark:border-purple-800/60">
              Super Admin
            </span>
          } @else {
            <span class="text-xs font-semibold uppercase tracking-wider text-amber-800 dark:text-amber-300 bg-amber-50 dark:bg-amber-950/60 px-2 py-0.5 rounded border border-amber-200 dark:border-amber-800/60">
              Store Owner
            </span>
          }
        </div>
        <p class="text-xs text-slate-500 dark:text-slate-400 truncate max-w-xs">
          @if (authStore.isStoreOwner() && storeState.activeStore()) {
            Assigned Merchant: <strong class="text-slate-800 dark:text-slate-200">{{ storeState.activeStore()?.name }}</strong>
          } @else {
            Marketplace Control Plane
          }
        </p>
      </div>
    </div>
  </div>

  <!-- Right: Theme Switcher & Profile -->
  <div class="flex items-center space-x-3 sm:space-x-4">
    <!-- Active Counters -->
    @if (authStore.isStoreOwner()) {
      <a
        routerLink="/store-owner/orders"
        class="hidden sm:flex items-center space-x-2 px-3 py-1.5 rounded-lg bg-amber-50 dark:bg-amber-950/50 border border-amber-200 dark:border-amber-800 text-amber-800 dark:text-amber-300 text-xs font-medium hover:bg-amber-100 dark:hover:bg-amber-900/40 transition"
      >
        <span class="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
        <span>Packing Queue: <strong class="text-amber-900 dark:text-amber-200">{{ orderState.pendingPackingCount() }}</strong></span>
      </a>
    } @else if (authStore.isSuperAdmin()) {
      <a
        routerLink="/super-admin/logistics"
        class="hidden sm:flex items-center space-x-2 px-3 py-1.5 rounded-lg bg-sky-50 dark:bg-sky-950/50 border border-sky-200 dark:border-sky-800 text-sky-800 dark:text-sky-300 text-xs font-medium hover:bg-sky-100 dark:hover:bg-sky-900/40 transition"
      >
        <span class="w-2 h-2 rounded-full bg-sky-500"></span>
        <span>Logistics In-Transit: <strong class="text-sky-900 dark:text-sky-200">{{ orderState.inTransitCount() }}</strong></span>
      </a>
    }

    <!-- Dark / Light Mode Toggle Button -->
    <button
      type="button"
      id="theme-toggle-btn"
      (click)="toggleTheme()"
      [title]="themeService.isDark() ? 'Switch to Light Mode' : 'Switch to Dark Mode'"
      aria-label="Toggle dark and light mode"
      class="relative p-2 sm:px-3 sm:py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800/80 hover:bg-slate-200 dark:hover:bg-slate-700/80 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 transition-all flex items-center space-x-2 focus:outline-none focus:ring-2 focus:ring-indigo-500 shadow-xs"
    >
      @if (themeService.isDark()) {
        <svg class="w-4 h-4 text-amber-400 animate-in spin-in-180 duration-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
        </svg>
        <span class="text-xs font-semibold hidden md:inline text-slate-200">Light</span>
      } @else {
        <svg class="w-4 h-4 text-slate-600 dark:text-slate-400 animate-in spin-in-180 duration-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9 0 0012 21a9.003 9 0 008.354-5.646z" />
        </svg>
        <span class="text-xs font-semibold hidden md:inline text-slate-700">Dark</span>
      }
    </button>

     <!-- Profile Dropdown -->
     <div class="relative">
       <button
         type="button"
         (click)="isProfileOpen.set(!isProfileOpen())"
         class="flex items-center space-x-3 p-1.5 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800/80 transition cursor-pointer"
       >
         <img
           [src]="authStore.user()?.avatarUrl"
           alt="Avatar"
           class="w-8 h-8 rounded-full object-cover ring-1 ring-slate-300 dark:ring-slate-600"
         />
         <div class="hidden md:block text-left">
           <div class="text-xs font-semibold text-slate-800 dark:text-slate-200 leading-tight">
             {{ authStore.user()?.name }}
           </div>
           <div class="text-[10px] font-mono text-indigo-600 dark:text-indigo-400 font-semibold">
             {{ authStore.user()?.role }}
           </div>
         </div>
         <svg class="w-3.5 h-3.5 text-slate-400 hidden md:block" fill="none" stroke="currentColor" viewBox="0 0 24 24">
           <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
         </svg>
       </button>

       @if (isProfileOpen()) {
         <div class="absolute right-0 top-11 mt-2 w-72 rounded-2xl bg-white dark:bg-[#0b131c] border border-slate-200 dark:border-slate-800 shadow-2xl py-2 z-50">
           <div class="px-4 py-3 border-b border-slate-100 dark:border-slate-800">
             <div class="flex items-center space-x-3">
               <img
                 [src]="authStore.user()?.avatarUrl"
                 alt="Avatar"
                 class="w-10 h-10 rounded-full object-cover ring-2 ring-indigo-500/50"
               />
               <div class="min-w-0">
                 <div class="text-sm font-bold text-slate-900 dark:text-white truncate">
                   {{ authStore.user()?.name }}
                 </div>
                 <div class="text-[10px] font-mono text-indigo-600 dark:text-indigo-400 font-semibold">
                   {{ authStore.user()?.role }}
                 </div>
               </div>
             </div>
           </div>

           <div class="p-2">
             <button
               (click)="logout()"
               class="w-full text-left px-3 py-2 text-xs font-semibold rounded-lg text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/30 flex items-center space-x-2 cursor-pointer"
             >
               <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                 <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
               </svg>
               <span>Sign Out</span>
             </button>
           </div>
         </div>
       }
     </div>
  </div>
</header>
